services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=otp
      - POSTGRES_USER=otp
      - POSTGRES_PASSWORD=otp
    ports:
      - "5432:5432"
