spring:
  application:
    name: demo-application
  profiles:
    default: calculator,catalog,one-time-password
  web:
    error:
      whitelabel:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.elasticsearch.autoconfigure.ElasticsearchClientAutoConfiguration
      - org.springframework.boot.elasticsearch.autoconfigure.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.data.elasticsearch.autoconfigure.DataElasticsearchAutoConfiguration
      - org.springframework.boot.data.elasticsearch.autoconfigure.DataElasticsearchRepositoriesAutoConfiguration
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    connection-timeout: 2s
    socket-timeout: 5s
one-time-password:
  length: 6
  max-attempts: 3
  expire-time: 5m
  rate-limit:
    generate:
      short:
        limit: 1
        duration: 30s
      long:
        limit: 5
        duration: 1h
    verify:
      long:
        limit: 10
        duration: 5m
---
spring:
  config:
    activate:
      on-profile: catalog
  autoconfigure:
    exclude: []
